# Setting the Stage

Este capítulo te ayudará a configurar nuestro entorno de trabajo. Debo señalar que el sistema operativo esperado para el aprendizaje profundo es Linux, con la mayoría de las cosas funcionando también bajo macOS. Windows suele ser considerado secundario, y muchos puertos de herramientas de aprendizaje profundo están mal mantenidos, aunque esto está mejorando con el tiempo.

Comenzaremos con algunas instrucciones para instalar los paquetes de software esperados. Luego echaremos un vistazo rápido a la biblioteca NumPy para Python 3.x. NumPy es fundamental para prácticamente todos los usos científicos de Python, y es esencial que sepas cómo trabajar con él a un nivel básico. A continuación, presentaré SciPy. Esta es también una herramienta necesaria para la ciencia, pero solo necesitaremos la parte más pequeña de ella aquí. Finalmente, hablaré un poco sobre la herramienta Scikit-Learn, abreviada aquí como sklearn. Esta valiosa herramienta implementa muchos de los modelos tradicionales de aprendizaje automático.

A lo largo del libro, a menudo utilizaré ejemplos en ejecución para ilustrar conceptos. Todos los fragmentos de código asumen que se ha ejecutado la siguiente línea:

In [2]:
import numpy as np

Además, en algunos lugares, el código hará referencia a la salida de un fragmento que apareció anteriormente en el capítulo. Los ejemplos de código son breves, por lo que seguir uno tras otro no debería ser una carga. Recomiendo dejar una sola sesión de Python en ejecución mientras trabajas en un capítulo, aunque esto no es necesario.

## Numpy

Ahora introduciré algunos conceptos básicos y manipulaciones de NumPy. Un tutorial completo está disponible en línea en [https://docs.scipy.org/doc/numpy/user/quickstart.html](https://docs.scipy.org/doc/numpy/user/quickstart.html).


In [5]:
print(f'Versión de NumPy: {np.__version__}')

Versión de NumPy: 1.26.4


La primera línea carga NumPy y establece un nombre abreviado para él, np. Usar el nombre abreviado no es necesario, pero hacerlo es casi universal. Asumiremos np en adelante. La segunda línea muestra la versión. Debería ser al menos lo que se muestra arriba.

### Definiendo arrays

NumPy opera en arrays y es bastante bueno convirtiendo listas en arrays. Piensa en el tipo de arrays que uno encuentra en un lenguaje como C o Java. NumPy proporciona una ventaja porque aunque Python es elegante, es demasiado lento para usos científicos cuando se simulan arrays con listas. Los arrays reales son mucho más rápidos. Aquí tienes un ejemplo que define un array a partir de una lista, y luego examina algunas de sus propiedades:

In [6]:
a = np.array([1,2,3,4])
print(f'Array definido: {a}')
print(f'Tamaño del array: {a.size}')
print(f'Forma del array: {a.shape}')
print(f'Tipo de datos del array: {a.dtype}')

Array definido: [1 2 3 4]
Tamaño del array: 4
Forma del array: (4,)
Tipo de datos del array: int32


Este ejemplo define una lista de cuatro elementos y luego la pasa a np.array para convertirla en un array de NumPy. Las propiedades básicas de un array incluyen el tamaño y la forma. El tamaño es de cuatro elementos. La forma también es cuatro, como una tupla, lo que muestra que a es un vector, un array unidimensional (1D). La forma es cuatro porque el array a tiene cuatro elementos. Si a fuera bidimensional (2D), la forma tendría dos valores, uno para cada eje del array. Mira el siguiente ejemplo, donde la forma de b nos dice que b tiene dos filas y cuatro columnas:


In [9]:
b = np.array([[1,2,3,4], [5,6,7,8]])
print(f'Array definido:\n {b}')
print(f'Tamaño del array: {b.size}')
print(f'Forma del array: {b.shape}')
print(f'Tipo de datos del array: {b.dtype}')

Array definido:
 [[1 2 3 4]
 [5 6 7 8]]
Tamaño del array: 8
Forma del array: (2, 4)
Tipo de datos del array: int32


### Tipos de datos


Los tipos de datos numéricos en Python vienen en dos variantes: enteros de tamaño arbitrario (intenta $2^{1000}$) o números de punto flotante. Sin embargo, NumPy permite arrays de muchos tipos diferentes. Bajo el capó, NumPy está implementado en C, por lo que soporta el mismo conjunto de tipos de datos que C. El ejemplo anterior muestra que la función np.array tomó la lista dada y, dado que cada elemento de la lista era un entero, creó un array donde cada elemento era un entero firmado de 64 bits. La siguiente tabla muestra los tipos de datos con los que trabaja NumPy; podemos dejar que NumPy elija el tipo de datos por nosotros, o podemos especificarlo explícitamente.

<center>

| Nombre en NumPy | Equivalencia en C  | Rango                           |
|------------|--------------------|---------------------------------|
| float64    | double             | $±[2.225 × 10^{-308}, 1.798 × 10^{308}]$ |
| float32    | float              | $±[1.175 × 10^{38}, 3.403 × 10^{38}]$     |
| int64      | long long          | $[–2^{63}, 2^{63−1}]$                 |
| uint64     | unsigned long long | $[0, 2^{64−1}]$                     |
| int32      | long               | $[–2^{31}, 2^{31−1}]$                 |
| uint32     | unsigned long      | $[0, 2^{32−1}]$                     |
| uint8      | unsigned char      | $[0, 255 = 2^{8−1}]$               |

</center>

Veamos algunos ejemplos de arrays con tipos de datos específicos:

In [10]:
a = np.array([1,2,3,4], dtype='uint8')
print(f'Tipo de datos del array: {a.dtype}')

a = np.array([1,2,3,4], dtype='uint16')
print(f'Tipo de datos del array: {a.dtype}')

a = np.array([1,2,3,4], dtype='uint32')
print(f'Tipo de datos del array: {a.dtype}')

b = np.array([1,2,3,4.0])
print(f'Tipo de datos del array: {b.dtype}')

b = np.array([1,2,3,4.0], dtype='float32')
print(f'Tipo de datos del array: {b.dtype}')

c = np.array([111,222,333,444], dtype='uint8')
print(f'Tipo de datos del array: {c.dtype}')

Tipo de datos del array: uint8
Tipo de datos del array: uint16
Tipo de datos del array: uint32
Tipo de datos del array: float64
Tipo de datos del array: float32
Tipo de datos del array: uint8


C:\Users\Javie\AppData\Local\Temp\ipykernel_23932\3262315278.py:16: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 333 to uint8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  c = np.array([111,222,333,444], dtype='uint8')
C:\Users\Javie\AppData\Local\Temp\ipykernel_23932\3262315278.py:16: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 444 to uint8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  c = np.array([111,222,333,444], dtype='uint8')


Los ejemplos con el array $a$ utilizan tipos de datos enteros, y los ejemplos con el array $b$ utilizan tipos de datos de punto flotante. Observa que el primer ejemplo con b se predeterminó a un flotante de 64 bits. NumPy hizo esto porque uno de los elementos de la lista de entrada era un flotante (4.0).

El último ejemplo que define el array $c$ parece ser un error. Pero no lo es. NumPy no nos avisa si el tipo de datos solicitado no puede contener los valores dados. Aquí, tenemos un entero de 8 bits que solo puede contener valores en el rango [0, 255]. Los dos primeros, 111 y 222, caben, pero los dos últimos, 333 y 444, son demasiado grandes. NumPy silenciosamente mantuvo solo los 8 bits más bajos de estos valores, que corresponden a 77 y 188, respectivamente. La lección es que NumPy espera que sepas lo que estás haciendo en cuanto a los tipos de datos. Por lo general, esto no es un problema, pero es algo para tener en cuenta.

### Arrays bidimensionales

Si una lista se convierte en un vector 1D, podríamos sospechar que una lista de listas se convertiría en un array 2D. Y tendríamos razón.

In [11]:
d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(f'Array definido:\n {d}')
print(f'Tamaño del array: {d.size}')
print(f'Forma del array: {d.shape}')
print(f'Tipo de datos del array: {d.dtype}')

Array definido:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Tamaño del array: 9
Forma del array: (3, 3)
Tipo de datos del array: int32


Vemos que una lista de tres sublistas se mapea a un array 3 × 3 (una matriz). Los subíndices en los arrays de NumPy comienzan desde cero, por lo que al hacer referencia a d[1,2] arriba, obtenemos 6.

### Ceros y unos

Dos funciones particularmente útiles de NumPy son np.zeros y np.ones. Ambas definen arrays dada una forma. La primera inicializa los elementos del array a cero, mientras que la segunda los inicializa a uno. Esta es la forma principal de crear arrays de NumPy desde cero.

In [13]:
a = np.arange(12).reshape((3,4))
print(f'Array definido:\n {a}')

a[1] = [44,55,66,77]
print(f'Array modificado:\n {a}')

Array definido:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Array modificado:
 [[ 0  1  2  3]
 [44 55 66 77]
 [ 8  9 10 11]]


Este ejemplo introduce np.arange, que es el equivalente de NumPy a la función range de Python. Observa el uso del método reshape para cambiar el vector de 12 elementos en una matriz 3 × 4. Además, observa que a[1] devuelve todo el subarreglo, comenzando con el primer índice de la primera dimensión. Esta sintaxis es una abreviatura de a[1,:] donde : significa todos los elementos de la dimensión dada. Esta abreviatura también funciona para asignaciones, como muestra la siguiente línea.

La misma sintaxis para indexar segmentos de una lista de Python funciona con NumPy. Así es como se vería si continuamos con el ejemplo anterior:

In [16]:
print(f'Muestra de un rango de la matriz:\n {a[:2]}')
print(f'Muestra de un rango de la matriz:\n {a[:2,:]}')
print(f'Muestra de un rango de la matriz:\n {a[:2,:3]}')

b = np.arange(12)
print(f'Array definido:\n {b}')
print(f'Muestra de un rango de la matriz:\n {b[::2]}')
print(f'Muestra de un rango de la matriz:\n {b[::3]}')
print(f'Muestra de un rango de la matriz:\n {b[::-1]}')

Muestra de un rango de la matriz:
 [[ 0  1  2  3]
 [44 55 66 77]]
Muestra de un rango de la matriz:
 [[ 0  1  2  3]
 [44 55 66 77]]
Muestra de un rango de la matriz:
 [[ 0  1  2]
 [44 55 66]]
Array definido:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Muestra de un rango de la matriz:
 [ 0  2  4  6  8 10]
Muestra de un rango de la matriz:
 [0 3 6 9]
Muestra de un rango de la matriz:
 [11 10  9  8  7  6  5  4  3  2  1  0]


Vemos que a[:2] devuelve las dos primeras filas con un $:$ implícito para la segunda dimensión, como muestra la línea siguiente. Con nuestro tercer comando, obtenemos un subarreglo en dos dimensiones tomando las dos primeras filas y las tres primeras columnas con a[:2,:3]. Los ejemplos con b muestran cómo extraer cada otro o cada tercer elemento. El último ejemplo es particularmente útil: utiliza un decremento negativo para invertir la dimensión. El decremento es –1 para invertir todos los valores. Si fuera –2, obtendríamos cada otro elemento de $b$ en orden inverso.

NumPy utiliza $:$ para indicar todos los elementos a lo largo de una dimensión específica. También permite usar $...$ (elipsis) como una abreviatura de "tantos : como sean necesarios". Por ejemplo, vamos a definir un array tridimensional (3D):

In [17]:
a = np.arange(24).reshape((4,3,2))
print(f'Array definido:\n {a}')

Array definido:
 [[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]


Puedes pensar en el array a como una colección de cuatro matrices 3 × 2. Para actualizar la segunda de estas matrices, podrías usar lo siguiente:

In [18]:
a[1,:,:] = [[11,22],[33,44],[55,66]]
print(f'Array modificado:\n {a}')

Array modificado:
 [[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[11 22]
  [33 44]
  [55 66]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]


Aquí, especificamos las dimensiones explícitamente con : y mostramos que NumPy no es quisquilloso: sabe que una lista de listas coincide con la forma esperada del subarreglo y actualiza el array a en consecuencia. Obtenemos el mismo efecto al usar los puntos suspensivos como se ve a continuación.

In [19]:
a[2,...] = [[99,99],[99,99],[99,99]]
print(f'Array modificado:\n {a}')

Array modificado:
 [[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[11 22]
  [33 44]
  [55 66]]

 [[99 99]
  [99 99]
  [99 99]]

 [[18 19]
  [20 21]
  [22 23]]]


### Leer y escribir en el disco

Los arrays de NumPy pueden ser escritos en y cargados desde el disco usando np.save y np.load, de la siguiente manera:

In [22]:
a = np.random.randint(0,5,(3,4))
print(f'Array definido:\n {a}')

np.save("./numpy/random.npy",a)
b = np.load("./numpy/random.npy")
print(f'Array obtenido del disco:\n {b}')

Array definido:
 [[2 0 3 0]
 [0 0 3 0]
 [0 1 2 2]]
Array obtenido del disco:
 [[2 0 3 0]
 [0 0 3 0]
 [0 1 2 2]]


Aquí, estamos usando np.random.randint para crear un array de enteros aleatorio de 3 × 4 con valores en el rango de 0 a 5. NumPy tiene extensas bibliotecas para números aleatorios. Escribimos el array a en el disco como random.npy. La extensión .npy es necesaria y se agregará si no la proporcionamos. Luego cargamos el array de vuelta desde el disco usando np.load.

Encontraremos otras funciones de NumPy a lo largo del libro. Las explicaré cuando se introduzcan por primera vez. Ahora pasemos a echar un vistazo rápido a la biblioteca SciPy.

## SciPy

SciPy añade una gran cantidad de funcionalidades a Python. Utiliza NumPy bajo el capó, por lo que a menudo se instalan juntos. Un tutorial completo está disponible aquí: [https://docs.scipy.org/doc/scipy/reference/tutorial/index.html](https://docs.scipy.org/doc/scipy/reference/tutorial/index.html).
En este libro, nos enfocaremos en las funciones del módulo scipy.stats.

In [23]:
import scipy
print(f'Versión de SciPy: {scipy.__version__}')

Versión de SciPy: 1.12.0


Esto carga el módulo SciPy y verifica que el número de versión sea al menos lo que debería ser. Cualquier versión posterior de SciPy debería funcionar bien. Como prueba rápida, intentemos lo siguiente:

In [26]:
from scipy.stats import ttest_ind

a = np.random.normal(0,1,1000)
b = np.random.normal(0,0.5,1000)
c = np.random.normal(0.1,1,1000)

print(f'Evaluación entre a y b: {ttest_ind(a,b)}')
print(f'Evaluación entre a y c: {ttest_ind(a,c)}')

Evaluación entre a y b: TtestResult(statistic=0.5843080173337849, pvalue=0.559079064489957, df=1998.0)
Evaluación entre a y c: TtestResult(statistic=-1.2194331650219166, pvalue=0.22282376186974148, df=1998.0)


Primero cargamos NumPy y luego la función `ttest_ind` del módulo `stats` de SciPy. Esta función toma dos conjuntos de datos, como puntajes de prueba de dos clases, y plantea la pregunta: ¿estos conjuntos de datos tienen el mismo valor promedio? O, más precisamente, pregunta: ¿con qué fuerza podemos creer que el mismo proceso generó estos dos conjuntos de datos? El test $t$ es un método clásico para responder a esta pregunta. Una forma de evaluar su resultado es observar el valor $p$. Puedes pensar en un valor $p$ como la probabilidad de que los dos conjuntos tengan la diferencia medida en el valor promedio si provienen del mismo proceso generador. Una probabilidad cercana a 1 significa que tenemos mucha confianza en que los dos conjuntos provienen del mismo proceso.

Las variables `a`, `b` y `c` son arrays unidimensionales donde los valores del array (aquí 1,000) se extraen de curvas gaussianas, también llamadas curvas normales. Llegaremos a esto más tarde, pero por ahora, sabemos que los números se extraen de una curva de campana donde los valores cerca del medio son más propensos a ser seleccionados que aquellos cerca de los bordes. Los dos primeros argumentos para `normal` son el valor promedio y la desviación estándar, una medida de cuán dispersa está la curva de campana: cuanto mayor sea la desviación estándar, más plana y ancha será la curva.

Para este ejemplo, esperaríamos que `a` y `b` fueran muy similares, ya que ambos tienen un valor promedio de 0.0, aunque con formas ligeramente diferentes de curvas de campana. Sin embargo, `c` tiene un valor promedio de 0.1. Esperamos que el test $t$ detecte esto y nos indique que debemos tener cuidado al creer que `a` y `c` fueron generados por el mismo proceso.

La salida de la función `ttest_ind` enumera el valor $p$ (p-value). Y, como esperábamos, comparar `a` y `b` devuelve un valor $p$ de 0.98, lo que significa que la probabilidad de ver la diferencia entre los promedios de estos dos conjuntos de datos, dado que provienen del mismo proceso generador, es aproximadamente del 98 por ciento. Sin embargo, cuando comparamos `a` y `c`, obtenemos un valor $p$ del 2.7 por ciento (0.027). Esto significa que hay aproximadamente un 3 por ciento de posibilidades de que veamos la diferencia entre `a` y `c` si fueran generados por el mismo proceso. Por lo tanto, concluimos que `a` y `c` provienen de procesos diferentes. Decimos, entonces, que la diferencia entre estos dos conjuntos de datos es estadísticamente significativa.

Históricamente, los valores $p$ inferiores a 0.05 se han considerado estadísticamente significativos. Sin embargo, este umbral es arbitrario, y la experiencia reciente en la replicación de experimentos, especialmente en las ciencias sociales, ha llevado a pedir un umbral más estricto. Usar un valor $p$ de 0.05 significa que estarás equivocado aproximadamente 1 vez de cada 20 (1/20 = 0.05), lo cual es un umbral demasiado generoso. Dicho esto, un valor $p$ cercano a 0.05 sugiere que algo está sucediendo, y se justifica una mayor investigación (y un conjunto de datos más grande).


## Matplotlib

Usaremos Matplotlib para generar gráficos. Verifiquemos sus capacidades de trazado 2D y 3D aquí. Primero, un ejemplo simple en 2D:

In [ ]:
import matplotlib.pylab as plt
x = np.random.random(100)
plt.plot(x)
plt.show()